### ISSUE TITLE
Invoice form link to 'deleted form'.

### ISSUE THREAD

**Issue by arpee** [w3f/Grant-Milestone-Delivery#187]
The [invoice form link](https://forms.gle/8Wx7nxtq8fKrsuEz8) in line seven of ```deliveries/milestone-delivery-template.md``` is returning a google error: 

```
Sorry, the file you have requested has been deleted.

Make sure that you have the correct URL and the owner of the file hasn't deleted it.
```

**Comment by semuelle** [comment]
Thanks for raising this, Richard!
