### ISSUE TITLE
Broken link - On chain identity

### ISSUE THREAD

**Issue by alijnmerchant21** [w3f/Grant-Milestone-Delivery#481]
For external evaluators, the first requirement is the on-chain identity of Kusama. 

https://guide.kusama.network/docs/mirror-learn-identity

The link mentioned above seems to be broken.

**Comment by lucasvanmol** [comment]
[Fixed](https://github.com/w3f/Grant-Milestone-Delivery/commit/0b09a4361b16ea082be389e325adfd6414cd935c), thanks!
