### ISSUE TITLE
Maintanance deliveries are not added to google sheets

### ISSUE THREAD

**Issue by lucasvanmol** [w3f/Grant-Milestone-Delivery#521]
e.g. https://github.com/w3f/Grant-Milestone-Delivery/pull/520 caused the following run:

https://github.com/w3f/Grant-Milestone-Delivery/actions/runs/2781261348

The file is not detected by the workflow due to this line:

https://github.com/w3f/Grant-Milestone-Delivery/blob/73d586e4578a3b11078eb464b4580487546356a5/.github/workflows/google_sheet_update.yml#L18

**Comment by takahser** [comment]
Thx for reporting.
You're right, we'll need to include `'maintenance_deliveries/*.md'` as well here.

The easiest would probably be to replace the current filter with:

```yml
filter: '*deliveries/*.md' 
```

`*deliveries` would then match `deliveries` as well as `maintenance_deliveries`.
Using an "or" expression would probably be more accurate, but I can't find any mention of it in the [filter pattern cheat sheet](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet).
