### ISSUE TITLE
Must Fill out the invoice form？

### ISSUE THREAD

**Issue by SinyuWei** [w3f/Grant-Milestone-Delivery#564]
As a freelance creator, I am an active developer in the Polkadot community. I have contributed to the community and am ready to contribute my code. But I don't know why the foundation has such an unreasonable request for me to fill in the invoice, which is not decentralized. And it has nothing to do with my contribution to the community and will dampen my enthusiasm. As a blockchain developer, I don't want to expose my personal information.

**Comment by Noc2** [comment]
It’s a legal requirement for a foundation in Switzerland. There is always the option to apply for treasury funding instead: https://github.com/w3f/Grants-Program#treasury Let me know if you have any other questions.

**Comment by SinyuWei** [comment]
> It’s a legal requirement for a foundation in Switzerland. There is always the option to apply for treasury funding instead: https://github.com/w3f/Grants-Program#treasury Let me know if you have any other questions.

I have a personal project to apply for a grant, but there is no company. Does it mean that if I want to apply for 10,000 usdt, I need to create a company first
