### ISSUE TITLE
What is invoice form ?

### ISSUE THREAD

**Issue by icodezjb** [w3f/Grant-Milestone-Delivery#749]
If the invoice pdf file is necessary to complete the grant, please provide some templates.

For previously completed grants, their invoice form pdf files can be made public, providing reference for future projects. is right ?

**Comment by semuelle** [comment]
What goes into an invoice is subject to the laws of Switzerland (where the Web3 Foundation is located) and the country you or your company is registered in. Therefore, we don't have a universal template. However, if you follow the [link to our invoice form](https://forms.gle/LSRr7PCjBpEbKGh89), it will tell you which information is required from our point of view. 

In some cases, the invoices contain private names and addresses, which is not something we want to force grant recipients to publish online.

**Comment by icodezjb** [comment]
Follow the [link to our invoice form](https://forms.gle/LSRr7PCjBpEbKGh89),  in the last item - "Please upload your invoice as a PDF.".
I'm very sorry I really don't know what kind of pdf file to upload.

**Comment by semuelle** [comment]
I don't know under which jurisdiction you or your company is under, so I cannot tell you what the invoice should look like. But, for example, if you were based in Singapore, you could search online for "singapore invoice template" and find [this website](https://create.onlineinvoices.com/templates/singapore-gst-invoice-template). All I can tell is you to please make sure that all data required from us, as described in the invoice form, is included.
