### ISSUE TITLE
URGENT: Wrong payment address in invoice 

### ISSUE THREAD

**Issue by salaheldinsoliman** [w3f/Grant-Milestone-Delivery#839]
Hello, It seems that I have uploaded a wrong public address for my payment for https://github.com/w3f/Grants-Program/pull/1334/files .
I have completed the first milestone and filled the invoice. please contact me asap regarding this issue. Thanks
@

**Comment by salaheldinsoliman** [comment]
@Noc2 @keeganquigley @dsm-w3f

**Comment by Noc2** [comment]
See https://github.com/w3f/Grants-Program/issues/1688#issuecomment-1517724851
